# Generated by Django 5.2.6 on 2025-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('is_new', models.BooleanField(default=False)),
            ],
        ),
    ]
