# Generated by Django 5.2.6 on 2025-10-15 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_application_job_application_job_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(default='CSE Department • University Campus', max_length=200)),
                ('opportunity_type', models.CharField(choices=[('teaching', 'Teaching Assistant'), ('research', 'Research Assistant'), ('part_time', 'Part Time'), ('internship', 'Internship')], max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('expected_applicants', models.IntegerField(default=0)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.ManyToManyField(blank=True, through='myapp.FacultyApplication', to='myapp.student')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='facultyapplication',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultyopportunity'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyapplication',
            unique_together={('student', 'opportunity')},
        ),
    ]
