# Generated by Django 5.2.6 on 2025-09-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='posted',
            field=models.CharField(default='Anytime', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('intern', 'Internship')], max_length=50),
        ),
    ]
