# Generated by Django 5.2.6 on 2025-10-16 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_companyjob_companyapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='facultyopportunity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('draft', 'Draft'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('verification', 'Verification'), ('user_management', 'User Management'), ('system', 'System')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.administrator')),
            ],
        ),
    ]
