# Generated by Django 5.2.6 on 2025-10-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_companyjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyopportunity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('draft', 'Draft'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
